/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ChannelPreviewIdRouteImport } from './routes/channel-preview.$id'
import { Route as GoUsernameRouteImport } from './routes/go.$username'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as RUsernameRouteImport } from './routes/r.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelPreviewIdRoute = ChannelPreviewIdRouteImport.update({
  id: '/channel-preview/$id',
  path: '/channel-preview/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GoUsernameRoute = GoUsernameRouteImport.update({
  id: '/go/$username',
  path: '/go/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RUsernameRoute = RUsernameRouteImport.update({
  id: '/r/$username',
  path: '/r/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRoute
  '/channels': typeof ChannelsRoute
  '/dashboard': typeof DashboardRoute
  '/progress': typeof ProgressRoute
  '/channel-preview/$id': typeof ChannelPreviewIdRoute
  '/go/$username': typeof GoUsernameRoute
  '/p/$id': typeof PIdRoute
  '/r/$username': typeof RUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRoute
  '/channels': typeof ChannelsRoute
  '/dashboard': typeof DashboardRoute
  '/progress': typeof ProgressRoute
  '/channel-preview/$id': typeof ChannelPreviewIdRoute
  '/go/$username': typeof GoUsernameRoute
  '/p/$id': typeof PIdRoute
  '/r/$username': typeof RUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRoute
  '/channels': typeof ChannelsRoute
  '/dashboard': typeof DashboardRoute
  '/progress': typeof ProgressRoute
  '/channel-preview/$id': typeof ChannelPreviewIdRoute
  '/go/$username': typeof GoUsernameRoute
  '/p/$id': typeof PIdRoute
  '/r/$username': typeof RUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/campaigns'
    | '/channels'
    | '/dashboard'
    | '/progress'
    | '/channel-preview/$id'
    | '/go/$username'
    | '/p/$id'
    | '/r/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/campaigns'
    | '/channels'
    | '/dashboard'
    | '/progress'
    | '/channel-preview/$id'
    | '/go/$username'
    | '/p/$id'
    | '/r/$username'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/campaigns'
    | '/channels'
    | '/dashboard'
    | '/progress'
    | '/channel-preview/$id'
    | '/go/$username'
    | '/p/$id'
    | '/r/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CampaignsRoute: typeof CampaignsRoute
  ChannelsRoute: typeof ChannelsRoute
  DashboardRoute: typeof DashboardRoute
  ProgressRoute: typeof ProgressRoute
  ChannelPreviewIdRoute: typeof ChannelPreviewIdRoute
  GoUsernameRoute: typeof GoUsernameRoute
  PIdRoute: typeof PIdRoute
  RUsernameRoute: typeof RUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel-preview/$id': {
      id: '/channel-preview/$id'
      path: '/channel-preview/$id'
      fullPath: '/channel-preview/$id'
      preLoaderRoute: typeof ChannelPreviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/$username': {
      id: '/go/$username'
      path: '/go/$username'
      fullPath: '/go/$username'
      preLoaderRoute: typeof GoUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$username': {
      id: '/r/$username'
      path: '/r/$username'
      fullPath: '/r/$username'
      preLoaderRoute: typeof RUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CampaignsRoute: CampaignsRoute,
  ChannelsRoute: ChannelsRoute,
  DashboardRoute: DashboardRoute,
  ProgressRoute: ProgressRoute,
  ChannelPreviewIdRoute: ChannelPreviewIdRoute,
  GoUsernameRoute: GoUsernameRoute,
  PIdRoute: PIdRoute,
  RUsernameRoute: RUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
